### ISSUE TITLE
feat(game): invite somebody to play

### ISSUE THREAD

**Issue by tyrossel** [Bima42/ft_transcendence#163]
### Workflow 

* [ ] Click "Invite to play" send a WS message to server
* [ ] Redirect demander to queue with a parameter `inviting` set to true
* [ ] The user can set the Game type, then click `invite` (instead of join) in order to send a WS message to server
* [ ] Server check if other user exists and is available
* [ ] If not possible, show an alert for the demander
* [ ] If possible, send a WS message to target user
* [ ] Show a confirm dialog for the target user  (with game type)
* [ ] If target user decline:
    - [ ] do nothing for him and send a `declineInvite` to server
    - [ ] server send a `invitationDeclined` to demander, which cancel the loading animation and prompt
* [ ] If target user accepts, redirect him to game view and send a `acceptInvite` to server
* [ ] Server starts game and send a `matchFound` to both user (no effect for target user)

### TODO

* [ ] PlayAGameView should continously ask the server for an available game
