### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by tyrossel** [Bima42/ft_transcendence#6]
Frontend 
-----------
- [x] Make left menu reactive to current location 
- [x] #20
- [x] #21
  - [x] Overflow on different pages
- [x] Create chat vue
  - [x] Figma and create several components
- [x] Create modalStore

Backend
-----------
- [x] #18
- [x] Create some User functions (add, delete, modify ...)
- [x] #34
- [x] #32
- [x] #46
- [x] #48
- [x] #42
- [x] Protect from SQL Injection

Game
-----------
- [x] Create a new component for the Pong game. (it will contain the HTML, CSS, and JavaScript necessary to run the game.)
  - [x] In the template section : 
    - [x] add a canvas element that will be used to draw the game elements (such as the ball and paddles).
    - [x] add controls for the game (such as buttons for starting and resetting the game).
  - [x] In the script section : 
    - [x] import the JavaScript file containing the code of the Pong game
- [x] Write the JavaScript code for the Pong game :
  - [x] Analyze the original pong and set the game rules : 
    - [x] The main features of the original Pong game were:
      - [x] Two paddles that could be moved up and down by the players
      - [x] A ball that bounced back and forth between the paddles
      - [x] A score that was incremented every time a player missed the ball with their paddle
      - [x] A simple "AI" that controlled the movement of the computer's paddle
  - [x] Create a canvas element and use JavaScript to : 
    - [x] draw shapes and images on the canvas
    - [x] handle user input and game logic.
    - [x] Game logic : 
      - [x] handle player input and update the positions of the ball and paddles.
      - [x] handle collisions/bounce between the ball and the paddles and the edges of the canvas.
      - [x] keep track of the score and end the game when one player reaches a certain number of points.
      - [x] A simple "AI" that controlled the movement of the computer's paddle
- [x] Our customize pong : 
  - [x] Adding features to the game : 
    - [x] ... ?
    - [x] ... ?

Docs
-----------
- [ ] Nest Authentication (+ guard, + Passport, + JWT strategy, + encryption)
- [ ] Typescript : await/async
- [ ] Nest : Dependency Injection
